// Generated by @wagmi/cli@1.1.0 on 7/5/2023 at 10:24:49 AM

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PrivateMarket
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const privateMarketABI = [
    {
        stateMutability: 'nonpayable',
        type: 'constructor',
        inputs: [
            {
                name: '_cancelBlockTime',
                internalType: 'uint256',
                type: 'uint256',
            },
        ],
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'Ask',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'AskCancelled',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'Bid',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'BidCancelled',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'Fill',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'Order',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'OrderAccepted',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: '',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'OrderCancelled',
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'a', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'b', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
            { name: 'c', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'input', internalType: 'uint256[10]', type: 'uint256[10]' },
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            { name: 'orderId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'acceptOrderETHAddress',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'a', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'b', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
            { name: 'c', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'input', internalType: 'uint256[57]', type: 'uint256[57]' },
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            { name: 'orderId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'acceptOrderSigMerkleGroth16Proof',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'a', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'b', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
            { name: 'c', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'input', internalType: 'uint256[11]', type: 'uint256[11]' },
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            { name: 'orderId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'acceptOrderSignature',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'price', internalType: 'uint256', type: 'uint256' },
            { name: 'keccakAddress', internalType: 'address', type: 'address' },
            { name: 'pubkey', internalType: 'uint256[2]', type: 'uint256[2]' },
        ],
        name: 'askETHAddress',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'price', internalType: 'uint256', type: 'uint256' },
            { name: 'vkeyHash', internalType: 'uint256', type: 'uint256' },
            { name: 'root', internalType: 'uint256', type: 'uint256' },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
        ],
        name: 'askSigMerkleGroth16Proof',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'price', internalType: 'uint256', type: 'uint256' },
            {
                name: 'signingKey',
                internalType: 'uint256[2]',
                type: 'uint256[2]',
            },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
        ],
        name: 'askSignature',
        outputs: [],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        name: 'asks',
        outputs: [
            { name: 'id', internalType: 'uint256', type: 'uint256' },
            {
                name: 'ordersCounter',
                internalType: 'struct Counters.Counter',
                type: 'tuple',
                components: [
                    {
                        name: '_value',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                ],
            },
            { name: 'from', internalType: 'address', type: 'address' },
            { name: 'status', internalType: 'uint256', type: 'uint256' },
            { name: 'cancelBlock', internalType: 'uint256', type: 'uint256' },
            {
                name: 'groth16proof',
                internalType: 'struct Market.Groth16SigMerkleProof',
                type: 'tuple',
                components: [
                    { name: 'price', internalType: 'uint256', type: 'uint256' },
                    {
                        name: 'vKeyhash',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    {
                        name: 'groupRoot',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                ],
            },
            {
                name: 'signature',
                internalType: 'struct Market.Signature',
                type: 'tuple',
                components: [
                    { name: 'price', internalType: 'uint256', type: 'uint256' },
                    {
                        name: 'signingKey',
                        internalType: 'uint256[2]',
                        type: 'uint256[2]',
                    },
                ],
            },
            {
                name: 'ethAddress',
                internalType: 'struct Market.EthAddress',
                type: 'tuple',
                components: [
                    { name: 'price', internalType: 'uint256', type: 'uint256' },
                    {
                        name: 'keccakAddress',
                        internalType: 'address',
                        type: 'address',
                    },
                ],
            },
        ],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'asksCounter',
        outputs: [{ name: '_value', internalType: 'uint256', type: 'uint256' }],
    },
    {
        stateMutability: 'payable',
        type: 'function',
        inputs: [
            { name: 'keccakAddress', internalType: 'address', type: 'address' },
            { name: 'poseidonNonce', internalType: 'uint256', type: 'uint256' },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
        ],
        name: 'bidETHAddress',
        outputs: [],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        name: 'bids',
        outputs: [
            { name: 'id', internalType: 'uint256', type: 'uint256' },
            { name: 'from', internalType: 'address', type: 'address' },
            { name: 'status', internalType: 'uint256', type: 'uint256' },
            { name: 'cancelBlock', internalType: 'uint256', type: 'uint256' },
            { name: 'poseidonNonce', internalType: 'uint256', type: 'uint256' },
            {
                name: 'ethAddress',
                internalType: 'struct Market.EthAddress',
                type: 'tuple',
                components: [
                    { name: 'price', internalType: 'uint256', type: 'uint256' },
                    {
                        name: 'keccakAddress',
                        internalType: 'address',
                        type: 'address',
                    },
                ],
            },
            {
                name: 'fill',
                internalType: 'struct Market.Fill',
                type: 'tuple',
                components: [
                    { name: 'from', internalType: 'address', type: 'address' },
                    {
                        name: 'fromPubkey',
                        internalType: 'uint256[2]',
                        type: 'uint256[2]',
                    },
                    {
                        name: 'orderedEthAddress',
                        internalType: 'struct Market.OrderedEthAddress',
                        type: 'tuple',
                        components: [
                            {
                                name: 'encryptedPrivKey',
                                internalType: 'uint256[7]',
                                type: 'uint256[7]',
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'bidsCounter',
        outputs: [{ name: '_value', internalType: 'uint256', type: 'uint256' }],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [{ name: 'askId', internalType: 'uint256', type: 'uint256' }],
        name: 'cancelAsk',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [{ name: 'bidId', internalType: 'uint256', type: 'uint256' }],
        name: 'cancelBid',
        outputs: [],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'cancelBlockTime',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            { name: 'orderId', internalType: 'uint256', type: 'uint256' },
            { name: 'typeOfOrder', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'cancelOrder',
        outputs: [],
    },
    {
        stateMutability: 'nonpayable',
        type: 'function',
        inputs: [
            { name: 'a', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'b', internalType: 'uint256[2][2]', type: 'uint256[2][2]' },
            { name: 'c', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'input', internalType: 'uint256[13]', type: 'uint256[13]' },
            { name: 'bidId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'fillETHAddressBid',
        outputs: [],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'fillsCounter',
        outputs: [{ name: '_value', internalType: 'uint256', type: 'uint256' }],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: 'askId', internalType: 'uint256', type: 'uint256' }],
        name: 'getAskPubKey',
        outputs: [{ name: '', internalType: 'uint256[2]', type: 'uint256[2]' }],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: 'bidId', internalType: 'uint256', type: 'uint256' }],
        name: 'getBidPubKey',
        outputs: [{ name: '', internalType: 'uint256[2]', type: 'uint256[2]' }],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: 'askId', internalType: 'uint256', type: 'uint256' }],
        name: 'getNOrdersForAskId',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [{ name: 'askId', internalType: 'uint256', type: 'uint256' }],
        name: 'getOrdersForAskId',
        outputs: [
            {
                name: '',
                internalType: 'struct Market.Order[]',
                type: 'tuple[]',
                components: [
                    { name: 'id', internalType: 'uint256', type: 'uint256' },
                    { name: 'from', internalType: 'address', type: 'address' },
                    {
                        name: 'status',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    { name: 'askId', internalType: 'uint256', type: 'uint256' },
                    {
                        name: 'orderType',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    {
                        name: 'fromPubKey',
                        internalType: 'uint256[2]',
                        type: 'uint256[2]',
                    },
                    {
                        name: 'cancelBlock',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    {
                        name: 'sharedKeyCommitment',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    {
                        name: 'poseidonNonce',
                        internalType: 'uint256',
                        type: 'uint256',
                    },
                    {
                        name: 'orderedGroth16SigMerkleProof',
                        internalType:
                            'struct Market.OrderedGroth16SigMerkleProof',
                        type: 'tuple',
                        components: [
                            {
                                name: 'messageHash',
                                internalType: 'uint64[4]',
                                type: 'uint64[4]',
                            },
                            {
                                name: 'encryptedProof',
                                internalType: 'uint256[49]',
                                type: 'uint256[49]',
                            },
                        ],
                    },
                    {
                        name: 'orderedSignature',
                        internalType: 'struct Market.OrderedSignature',
                        type: 'tuple',
                        components: [
                            {
                                name: 'messagePreImage',
                                internalType: 'uint256[2]',
                                type: 'uint256[2]',
                            },
                            {
                                name: 'message',
                                internalType: 'uint256',
                                type: 'uint256',
                            },
                            {
                                name: 'encryptedSignature',
                                internalType: 'uint256[4]',
                                type: 'uint256[4]',
                            },
                        ],
                    },
                    {
                        name: 'orderedEthAddress',
                        internalType: 'struct Market.OrderedEthAddress',
                        type: 'tuple',
                        components: [
                            {
                                name: 'encryptedPrivKey',
                                internalType: 'uint256[7]',
                                type: 'uint256[7]',
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        stateMutability: 'payable',
        type: 'function',
        inputs: [
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            {
                name: 'sharedKeyCommitment',
                internalType: 'uint256',
                type: 'uint256',
            },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'poseidonNonce', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'orderETHAddress',
        outputs: [],
    },
    {
        stateMutability: 'payable',
        type: 'function',
        inputs: [
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            {
                name: 'messageHash',
                internalType: 'uint64[4]',
                type: 'uint64[4]',
            },
            {
                name: 'sharedKeyCommitment',
                internalType: 'uint256',
                type: 'uint256',
            },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'poseidonNonce', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'orderSigMerkleGroth16Proof',
        outputs: [],
    },
    {
        stateMutability: 'payable',
        type: 'function',
        inputs: [
            { name: 'askId', internalType: 'uint256', type: 'uint256' },
            {
                name: 'messagePreImage',
                internalType: 'uint256[2]',
                type: 'uint256[2]',
            },
            { name: 'message', internalType: 'uint256', type: 'uint256' },
            {
                name: 'sharedKeyCommitment',
                internalType: 'uint256',
                type: 'uint256',
            },
            { name: 'pubKey', internalType: 'uint256[2]', type: 'uint256[2]' },
            { name: 'poseidonNonce', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'orderSignature',
        outputs: [],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'sellECDSAECDH',
        outputs: [
            { name: '', internalType: 'contract Verifier', type: 'address' },
        ],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'sellECDSANoECDH',
        outputs: [
            { name: '', internalType: 'contract Verifier', type: 'address' },
        ],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'sellEdDSASigVerifier',
        outputs: [
            { name: '', internalType: 'contract Verifier', type: 'address' },
        ],
    },
    {
        stateMutability: 'view',
        type: 'function',
        inputs: [],
        name: 'sellSigMerkleGroth16Verifier',
        outputs: [
            { name: '', internalType: 'contract Verifier', type: 'address' },
        ],
    },
] as const
